### ISSUE TITLE
感谢分享，只需要nahida.pt这个文件对吗？

### ISSUE THREAD

**Issue by autumoon** [710765989/my_textual_inversions#1]
还没有来得及测试，请问是只需要nahida.pt这个文件，其他文件都不需要对吗？

**Comment by 710765989** [comment]
是的 pt文件就是训练出来的模型

**Comment by autumoon** [comment]
感谢回复，刚刚测试了一下，可以跑出来，只是nahida的眼睛似乎都不太像（眼睛很关键），样例图也是（十字），是不是样本问题呀

顺便说下，注意事项：
1.nahida.pt放到\stable-diffusion-webui\embeddings
2.模型选择novelaifinal-pruned.ckpt，而不要选择sd-v1-4.ckpt 否则没结果
3.生成大小选择512*512，否则可能没有结果

**Comment by 710765989** [comment]
感谢回复

1.样本没问题 样本图眼睛都有四叶草标志 但是ai学不会呀
2.模型的话我是用的animefull-latest.ckpt(7g左右), 如果使用animefull-final-pruned.ckpt(4g左右)的话，生成出来的图片是各种很奇怪的烂图

**Comment by autumoon** [comment]
是的 模型使用的是7G左右的那个 这个7G的模型生成速度快一些 但稳定性感觉不如4G左右的那个

**Comment by 710765989** [comment]
生成速度不清楚 我一开始就是使用的4g模型 那根本不能训练模型 出来的结果你看我训练的草神前边的图就知道了 5万多step开始我才换成7g模型 一换就开始转向正常了

**Comment by autumoon** [comment]
这个倒是没注意测试 按道理应该都能训练 输出的 具体肯定以实践为准了
我现在已经把4G的那个模型删掉了 主要是因为7G的模型生成效率可以提高一倍以上（同样tag同样分辨率的图，生成耗时只需要原来的二分之一以下，而生成效果甚至有所提升）。
顺便，novelAI真好玩→_→

**Comment by 710765989** [comment]
看文件名字
animefull-latest.ckpt(7g)是最新版
animefull-final-pruned.ckpt(4g)是修剪版本

可能是删掉了训练模型用的那部分？

**Comment by autumoon** [comment]
名字参考意义不大，看文件大小，因为名字可以随便改，只要和权重文件保持一致即可。
7.17 GB (7,703,828,146 字节)

**Comment by 710765989** [comment]
嗯
