### ISSUE TITLE
那西坦的图全是绿色头发

### ISSUE THREAD

**Issue by aliencaocao** [710765989/my_textual_inversions#3]
![image](https://user-images.githubusercontent.com/20109683/203312783-241289e8-bf5d-49e2-a32e-11906a9f9dcc.png)
![image](https://user-images.githubusercontent.com/20109683/203312809-7049c26c-db77-40d8-bb03-86e3b7bb8a4b.png)
上面两张是用Anything V3.0生成的
下面两张是用animefull pruned生成的
![image](https://user-images.githubusercontent.com/20109683/203312968-4c0bd1aa-95e5-4d2b-96be-8f9ce65c5ed1.png)
![image](https://user-images.githubusercontent.com/20109683/203312979-afe66b63-a8cb-48fa-ba1f-b33e2ccd7217.png)

请问作者有没有遇到这样的问题？如何得到白色头发的那西坦？

**Comment by 710765989** [comment]
这个问题我视频里有说明 在纳西妲词条前加一个white hair词条就行了

**Comment by aliencaocao** [comment]
哦，所以是正常的是吧？我怕是我本地设置有问题

**Comment by 710765989** [comment]
是的 纳西妲绿色元素太多了 导致训练出来的头发和衣服都染成了绿色

**Comment by aliencaocao** [comment]
正常了，谢谢
